version: '3.8'
services:
  webapp:
    command: uwsgi --ini app.ini
    expose:
      - 5000
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
    depends_on:
      - postgres
  nginx:
    image: webapp-nginx
    build: ./nginx
    expose:
      1234
    depends_on:
      - webapp
  postgres:
    image: 'postgres:12.4-alpine'
    environment:
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_USER=student_user
      - POSTGRES_DB=labo
